### ISSUE TITLE
Product quantity should not be less than 0

### ISSUE THREAD

**Issue by mehtayash23** [nayanseth/ecommerce#1]
There is a small validation issue while updating the quantity of a product by admin. If the available product is 4 and admin chooses to reduce its quantity by 6, product quantity will be -2 which is wrong. It should not be less than 0.
There is another small issue too. If a new user does something wrong while registering on website, user is not getting the error, it just redirects to login.php without showing any error.

**Comment by nayanseth** [comment]
@mehtayash23 Agree. For the verification, I am not pretty sure. I think, I looked into it. Forgot about the zero thing while developing it. And as it was for a college project, I never really maintained it. If you would like to update the code, feel free to do so, I could push in your commit.

**Comment by mehtayash23** [comment]
@nayanseth Got you. Anyway, it was not a big issue and I have created a PR. You can commit if you want!

**Comment by nayanseth** [comment]
@mehtayash23 Thanks!
